name: Sync README.md to src/README.md

on:
  push:
    paths:
      - 'README.md'  # 当 README.md 文件发生变化时触发

jobs:
  sync-readme:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境来运行工作流

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 检出仓库代码

      - name: Copy README.md to src/README.md
        run: |
          cp README.md src/README.md  # 将 README.md 文件复制到 src 目录
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"  # 配置 git 用户名
          git config --global user.email "github-actions@github.com"  # 配置 git 邮箱
          git add src/README.md  # 将修改加入 git 暂存区
          git commit -m "Sync README.md to src/README.md" || echo "No changes to commit"  # 提交更改
          git push  # 推送更改到远程仓库
